/*

 SPACEHUNT_WINDOW.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\Chris\Downloads\gbtd\tilesets\spacehunt_bg.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define SpaceHuntWindowMapWidth 20
#define SpaceHuntWindowMapHeight 18
#define SpaceHuntWindowMapBank 0

extern unsigned char SpaceHuntWindowMap[];

/* End of SPACEHUNT_WINDOW.H */
